<?php
/**
 * @author    Agence Dn'D <magento@dnd.fr>
 * @copyright Copyright (c) 2015 Agence Dn'D (http://www.dnd.fr)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php $column  = $this->getColumn(); ?>
<?php $options = $this->getOptions(); ?>
<div>#{<?php echo $this->getColumnName() ?>}</div> <select name="<?php echo $this->getInputName() ?>"<?php if (isset($column['style'])): ?> style="<?php echo $column['style'] ?>"<?php endif; ?>><option value=""></option><?php foreach($options as $option): ?><option value="<?php echo $option['value'] ?>"><?php echo $option['label'] ?></option><?php endforeach; ?></select>