<?php
/**
 * @author    Agence Dn'D <magento@dnd.fr>
 * @copyright Copyright (c) 2015 Agence Dn'D (http://www.dnd.fr)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php $tasks = $this->getTasks(); ?>

<div class="task-command">
    <?php if(count($tasks)): ?>
        <select name="task-command" id="task-command">
            <option value=""><?php echo $this->__('Select') ?></option>
            <?php foreach($tasks as $command => $task): ?>
                <option value="<?php echo $command ?>"><?php echo $task['label'] ?></option>
            <?php endforeach; ?>
        </select>
    <?php else: ?>
        <p><?php echo $this->__('No task was found') ?></p>
    <?php endif; ?>
</div>

<div id="task-execute-zone">

    <form action="#" name="task-options" id="task-options"></form>

    <div id="tasks-types">
        <div id="type-file" class="task-execute" style="display:none">
            <div id="<?php echo $this->getHtmlId() ?>" class="uploader">
                <div class="buttons">
                    <?php echo $this->getBrowseButtonHtml(); ?>
                    <?php echo $this->getUploadButtonHtml(); ?>
                </div>
            </div>
            <div class="no-display" id="<?php echo $this->getElementId('template') ?>">
                <div id="{{id}}-container" class="file-row">
                    <span class="file-info">{{name}} {{size}}</span>
                    <span class="delete-button"><?php echo $this->getDeleteButtonHtml() ?></span>
                    <span class="progress-text"></span>
                    <div class="clear"></div>
                </div>
            </div>
            <div class="no-display" id="<?php echo $this->getHtmlId() ?>-template-progress">
                {{percent}}% {{uploaded}} / {{total}}
            </div>
            <?php echo $this->getChildHtml('additional_scripts'); ?>
        </div>
        <div id="type-button" class="task-execute" style="display:none">
            <?php echo $this->getExecuteButtonHtml() ?>
        </div>
    </div>

</div>

<script type="text/javascript">
//<![CDATA[
    function initUploader() {

        $$('#type-file .complete').each(function(item) {
            item.remove();
        });

        var uploader = new Uploader(<?php echo $this->getJsonConfig(); ?>);

        if (varienGlobalEvents) {
            varienGlobalEvents.attachEventHandler('tabChangeBefore', uploader.onContainerHideBefore);
        }

        uploader._handleDelete = function() {}; // We do not want to remove uploaded file container after upload.

        document.on('uploader:fileSuccess', function(event) {
            var id = event.memo.containerId;

            $$('#tasks-types .file-row.complete').each(function(elem) {
                elem.down('.progress-text').update(Translator.translate('Complete'));
            });

            var progress = $(id).down('.progress-text');

            progress.update($('type-button').innerHTML);
            progress.down().rel = event.memo.response.replace(/"/g, "");
        });
    }

    $('task-command').observe('change', function() {
        initUploader();
    });

    var taskExecutor = new TaskExecutor(
        '<?php echo $this->getUrl('adminhtml/task/launch') ?>',
        '<?php echo $this->getUrl('adminhtml/task/options') ?>',
        <?php echo $this->getTasksJson() ?>);
//]]>
</script>
